# This file was generated by 'extra-files-to-dist-gen.sh'. Do not modify.
extra_files_to_dist = \
doc/guide/10-getting-started.md \
doc/guide/60-standalone.md \
doc/guide/80-installation.md \
tests/README \
tests/auto/bit32.mcs \
tests/auto/fs.mcs \
tests/auto/fs_file.mcs \
tests/auto/magic_strict.mcs \
tests/auto/regex.mcs \
tests/benchmarks/treewalk/README \
tests/benchmarks/treewalk/bench.mcs \
tests/benchmarks/treewalk/bench.py \
tests/benchmarks/treewalk/bench.rb \
tests/benchmarks/treewalk/run.sh \
tests/nonauto/magic_table_gc.mcs \
tests/nonauto/mcscript_argv.mcs \
tests/nonauto/mcscript_error.mcs \
tests/nonauto/mcscript_error2.mcs \
tests/nonauto/vfs_bug_crash.mcs \
tests/nonauto/vfs_bug_errno_chdir.mcs \
tests/nonauto/vfs_bug_errno_open.mcs
