# MC developers: Run this script after you rename/remove/add files within this
# tree, if you want the 'make dist' command to reflect these changes.
#
# Don't forget to run 'autoreconf' afterwards.

(
echo "# This file was generated by 'extra-files-to-dist-gen.sh'. Do not modify."
echo "extra_files_to_dist = \\"
git ls-tree -r --name-only HEAD | grep -v gitignore | grep '^\(doc\|misc\|tests\)/' | sed '$q;s/$/ \\/'
) > extra-files-to-dist.mk
