# This file was generated by 'extra-files-to-dist-gen.sh'. Do not modify.
extra_files_to_dist = \
doc/guide/10-getting-started.md \
doc/guide/60-standalone.md \
doc/guide/80-installation.md \
tests/README \
tests/auto/bit32.mcs \
tests/auto/magic_strict.mcs \
tests/nonauto/mcscript_argv.mcs \
tests/nonauto/mcscript_error.mcs \
tests/nonauto/mcscript_error2.mcs
